FROM node:18-buster-slim

# set our node environment, either development or production
# defaults to production, compose overrides this to development on build and run
ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

ARG PORT=19000
ENV PORT $PORT
EXPOSE $PORT

# install global packages
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH /home/node/.npm-global/bin:$PATH
RUN npm i --unsafe-perm --allow-root -g npm@latest expo-cli@latest

# install dependencies first, in a different location for easier app bind mounting for local development
# due to default /opt permissions we have to create the dir with root and change perms
RUN mkdir /opt/detection-mobile
WORKDIR /opt/detection-mobile
ENV PATH /opt/detection-mobile /.bin:$PATH
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn

# copy in our source code last, as it changes the most
WORKDIR /opt/detection-mobile /app
# for development, we bind mount volumes; comment out for production
COPY . .

ENTRYPOINT ["yarn", "start"]
